#!/usr/bin/env bash

kubectl get pods --all-namespaces -o custom-columns=":metadata.namespace,:metadata.name,:status.phase,:status.reason" | grep Failed | grep Terminated | awk '{print $1, $2;}' | xargs -n2 kubectl delete pod -n
